export const GET_ISSUES_REQUEST = 'issues/GET_ISSUES_REQUEST'
export const GET_ISSUES_SUCCESS = 'issues/GET_ISSUES_SUCCESS'
export const GET_ISSUES_FAIL = 'issues/GET_ISSUES_FAIL'
export const SET_ASSIGNEE = 'issues/SET_ASSIGNEE'
export const SET_REPO = 'issues/SET_REPO'
